"""Add tracking_data column

Revision ID: 295c3a9c54e9
Revises: dacd9396c71d
Create Date: 2026-03-22 11:33:48.766527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '295c3a9c54e9'
down_revision: Union[str, Sequence[str], None] = 'dacd9396c71d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shot_measurements', sa.Column('tracking_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shot_measurements', 'tracking_data')
    # ### end Alembic commands ###
